<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rrp.Core\Rrp.Core.csproj" />
    <ProjectReference Include="..\Rrp.Windows\Rrp.Windows.csproj" />
  </ItemGroup>
</Project>
